name = "authserver"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[vars]
SEATABLE_SERVER_URL = "https://table.nju.edu.cn"

[[d1_databases]]
binding = "DB"
database_name = "authserver-db"
database_id = "c80c0aef-2ab2-4935-af3c-8fb7ecb259f6"
migrations_dir = "migrations"
