name = "authserver"
main = "src/index.ts"
compatibility_date = "2026-07-23"
compatibility_flags = ["nodejs_compat"]

[vars]
SEATABLE_SERVER_URL = "https://table.nju.edu.cn"

[[d1_databases]]
binding = "AUTH_DB"
database_name = "authserver"
database_id = "9ffad5cf-c66b-43b1-8641-edfa3d8f57d0"
migrations_dir = "migrations"
